version: '3.1'

services:
  impugnaciones:
    build: .
    image: impugnaciones:latest
    container_name: impugnaciones
    environment:
      ENVIRONMENT: development
    depends_on:
      - db
    volumes:
      - .:/src
      - ./scripts:/scripts
    # Dev user: admin pass: admin
    command: ["/scripts/wait-for-it.sh", "db:5432", "--", "/scripts/command-dev.sh"]
    ports:
      - "8008:8000"

  db:
    image: postgres:12
    container_name: impugnaciones-postgres
    environment:
      POSTGRES_DB: impugnaciones
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: postgres
